name: UX Scan (Public Runner)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to scan'
        required: true
        type: string
      scanType:
        description: 'Type of scan to perform'
        required: false
        default: 'full'
        type: string
      scanId:
        description: 'Unique scan ID'
        required: true
        type: string
      privateRepo:
        description: 'owner/repo of the private repository to scan (e.g. your-org/your-private-repo)'
        required: true
        type: string
      userQuery:
        description: 'User query for the scan'
        required: false
        default: 'Comprehensive UX analysis'
        type: string
      enableAI:
        description: 'Whether AI analysis is enabled for this user'
        required: false
        default: 'true'
        type: string
      blobToken:
        description: 'Vercel Blob Read/Write Token for screenshot storage'
        required: false
        type: string
      # NEW: Business context for next-gen analysis
      businessContext:
        description: 'Business context JSON for predictive analysis'
        required: false
        type: string
      # NEW: Enable next-gen features
      enableNextGen:
        description: 'Enable next-generation UX analysis features'
        required: false
        default: 'true'
        type: string
  repository_dispatch:
    types: [run-ux-scan]

permissions:
  contents: read
  actions: read

jobs:
  ux-scan:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 20  # Increased for next-gen analysis

    steps:
    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.privateRepo || github.event.client_payload.privateRepo }}
        token: ${{ secrets.PRIVATE_REPO_PAT }}
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install chromium

    - name: Validate AI access and next-gen features
      run: |
        # Get inputs from either workflow_dispatch or repository_dispatch
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          ENABLE_AI="${{ github.event.inputs.enableAI }}"
          USER_QUERY="${{ github.event.inputs.userQuery }}"
          ENABLE_NEXT_GEN="${{ github.event.inputs.enableNextGen }}"
          BUSINESS_CONTEXT="${{ github.event.inputs.businessContext }}"
        else
          ENABLE_AI="${{ github.event.client_payload.enableAI }}"
          USER_QUERY="${{ github.event.client_payload.userQuery }}"
          ENABLE_NEXT_GEN="${{ github.event.client_payload.enableNextGen }}"
          BUSINESS_CONTEXT="${{ github.event.client_payload.businessContext }}"
        fi

        # Validate AI access
        if [ "$ENABLE_AI" = "false" ] || [ "$ENABLE_AI" = "0" ]; then
          echo "AI analysis disabled for this user"
          echo "DISABLE_AI=true" >> $GITHUB_ENV
        else
          echo "AI analysis enabled for this user"
          echo "DISABLE_AI=false" >> $GITHUB_ENV
        fi

        # Validate next-gen features
        if [ "$ENABLE_NEXT_GEN" = "false" ] || [ "$ENABLE_NEXT_GEN" = "0" ]; then
          echo "Next-gen analysis disabled"
          echo "ENABLE_NEXT_GEN=false" >> $GITHUB_ENV
        else
          echo "Next-gen analysis enabled"
          echo "ENABLE_NEXT_GEN=true" >> $GITHUB_ENV
        fi

        # Set user query and business context with fallback
        echo "USER_QUERY=$USER_QUERY" >> $GITHUB_ENV
        
        # Handle business context - use default if empty or not provided
        if [ -z "$BUSINESS_CONTEXT" ] || [ "$BUSINESS_CONTEXT" = "" ]; then
          echo "Using default business context"
          BUSINESS_CONTEXT='{"industry":"Technology","businessType":"SaaS","targetAudience":"Developers and Designers","conversionGoals":["signup","trial","demo"],"monthlyRevenue":50000,"monthlyVisitors":10000,"averageOrderValue":100,"currentConversionRate":0.025,"competitivePosition":"challenger"}'
        fi
        echo "BUSINESS_CONTEXT=$BUSINESS_CONTEXT" >> $GITHUB_ENV

    - name: Run Enhanced UX scan with Next-Gen Analysis
      env:
        # Core AI APIs
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
        # Scan configuration
        DISABLE_AI: ${{ env.DISABLE_AI }}
        USER_QUERY: ${{ env.USER_QUERY }}
        ENABLE_NEXT_GEN: ${{ env.ENABLE_NEXT_GEN }}
        BUSINESS_CONTEXT: ${{ env.BUSINESS_CONTEXT }}
        
        # File storage
        BLOB_READ_WRITE_TOKEN: ${{ github.event.inputs.blobToken || github.event.client_payload.blobToken }}
        
        # Next-gen analysis features
        ENABLE_VISION_FIRST: ${{ env.ENABLE_NEXT_GEN }}
        ENABLE_INTERACTION_ANALYSIS: ${{ env.ENABLE_NEXT_GEN }}
        ENABLE_PREDICTIVE_INSIGHTS: ${{ env.ENABLE_NEXT_GEN }}
        ENABLE_COMPETITIVE_INTELLIGENCE: ${{ env.ENABLE_NEXT_GEN }}
      run: |
        # Get inputs from either workflow_dispatch or repository_dispatch
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          URL="${{ github.event.inputs.url }}"
          SCAN_TYPE="${{ github.event.inputs.scanType }}"
          SCAN_ID="${{ github.event.inputs.scanId }}"
        else
          URL="${{ github.event.client_payload.url }}"
          SCAN_TYPE="${{ github.event.client_payload.scanType }}"
          SCAN_ID="${{ github.event.client_payload.scanId }}"
        fi

        echo "🚀 Starting Enhanced UX scan with Next-Gen Analysis"
        echo "URL: $URL"
        echo "Scan type: $SCAN_TYPE"
        echo "Scan ID: $SCAN_ID"
        echo "User query: $USER_QUERY"
        echo "AI enabled: $([ "$DISABLE_AI" = "true" ] && echo "No" || echo "Yes")"
        echo "Next-gen features: $([ "$ENABLE_NEXT_GEN" = "true" ] && echo "Enabled" || echo "Disabled")"
        echo "Blob token available: $([ -n "$BLOB_READ_WRITE_TOKEN" ] && echo "Yes" || echo "No")"
        echo "Business context: $BUSINESS_CONTEXT"

        # Run the Enhanced UX scan script with next-gen parameters
        npx tsx scripts/enhanced-scan-runner.ts \
          --url="$URL" \
          --scan-type="$SCAN_TYPE" \
          --scan-id="$SCAN_ID" \
          --user-query="$USER_QUERY" \
          --disable-ai="$DISABLE_AI" \
          --enable-next-gen="$ENABLE_NEXT_GEN" \
          --business-context="$BUSINESS_CONTEXT"

    - name: Upload scan results and next-gen insights
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scan-results-${{ github.event.inputs.scanId || github.event.client_payload.scanId }}
        path: |
          scan-results-*.json
          screenshots/
          next-gen-insights-*.json
          predictive-analysis-*.json
        retention-days: 7

    - name: Notify completion with next-gen insights
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          SCAN_ID="${{ github.event.inputs.scanId }}"
          URL="${{ github.event.inputs.url }}"
        else
          SCAN_ID="${{ github.event.client_payload.scanId }}"
          URL="${{ github.event.client_payload.url }}"
        fi

        echo "🎉 Enhanced UX scan completed for $URL"
        echo "Scan ID: $SCAN_ID"
        echo "Results uploaded as artifact"
        echo "AI analysis: $([ "$DISABLE_AI" = "true" ] && echo "Disabled" || echo "Enabled")"
        echo "Next-gen features: $([ "$ENABLE_NEXT_GEN" = "true" ] && echo "Enabled" || echo "Disabled")"
        echo "Predictive insights: $([ "$ENABLE_NEXT_GEN" = "true" ] && echo "Generated" || echo "Not available")"
